### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by bobitza** [KillStr3aK/discord-server-manager#4]
I have error when compile discord_manager

![image](https://user-images.githubusercontent.com/1919467/112039897-34d44000-8b4d-11eb-8093-24ab50802f78.png)

**Comment by bobitza** [comment]
![image](https://user-images.githubusercontent.com/1919467/112039947-43225c00-8b4d-11eb-882d-9a2f69dbe7f7.png)

**Comment by KillStr3aK** [comment]
This source only compiles above 1.9
