### ISSUE TITLE
Question about plugins

### ISSUE THREAD

**Issue by Tarek8220** [KillStr3aK/discord-server-manager#8]
I downloaded DSM and when i open the plugin folder i see discord api and discord manager activated and the 2 same files inside the scripting but there is another one too called discord manager natives. whats the different between that one and the first one ?

and about the files inside the scripting/includes like just the discord.inc or servermanager.inc do i have to compile them to make it work or ? im little bit new to this sorry

**Comment by KillStr3aK** [comment]
this plugin is unfinished and no longer continued, I suggest you not to use it.
Use alternatives like [discord utilities](https://github.com/Cruze03/discord-utilities) however it may work differently.

**Comment by Tarek8220** [comment]
Aight, I downloaded the one you sent me. Looking inside the scripting folder i see 2 folders. Discord utilities and Include. Do i have to compile any of the files inside those 2 folders or will it still work if only discord_utilites.smx is activated? and what about steamworks and smjansson do i still need them ? sorry i ask to much but can't really find any guide on how to install the plugin you gave me. as i said im new to all that discord stuff so am trying my best :D

**Comment by KillStr3aK** [comment]
they're all dependencies so you need them aswell, however they are already compiled so you dont have to recompile them again. for quick questions you may want to add me on discord tho.

**Comment by Tarek8220** [comment]
I meant the files inside the Include folder. The inc files. Do i have to compile them to smx too or is discord_utilities.smx and smjanson and steamworks enough to make it work ? 
![image](https://user-images.githubusercontent.com/62396010/147874654-ad5d8ece-8369-4ef4-a846-5fb0dda6a585.png)

and actually i have alooot of questions xD soo if you don't mind please add me on discord or write your name and i will add you. Im already in your discord so i will assume you're Curuj but im not sure xD

2 Fat 2 Serious#9680

**Comment by KillStr3aK** [comment]
they're already compiled with the plugin, so you don't have to compile them.
KillStr3aK#9143
